### ISSUE TITLE
Problem with URDF_USE_SELF_COLLISION flag

### ISSUE THREAD

**Issue by Vvlad1slavV** [ITMORobotics/itmobotics_sim#1]
https://github.com/ITMORobotics/itmobotics_sim/blob/b336d91c8395f92126e78e5207f8994a9a55bf62/src/itmobotics_sim/pybullet_env/pybullet_robot.py#L292

Usage **URDF_USE_SELF_COLLISION** can create some BUGs, like mini jumping off model or incorrect model control. 

Please add an option to disable URDF_USE_SELF_COLLISION

**Comment by Vvlad1slavV** [comment]
And here, **useFixedBase** needs to add an option too

**Comment by TexnoMann** [comment]
Resolved in PR #17
