### ISSUE TITLE
New feature - contact force

### ISSUE THREAD

**Issue by Vvlad1slavV** [ITMORobotics/itmobotics_sim#2]
Contact strength detection functionality can be useful.
In my opinion, the function should return the following values:
1. contact states: bool
2. contact forces: float
3. contact direction 
4. friction coeff: float (if exist)

**Comment by TexnoMann** [comment]
About forces. You can get a vector of forces and torques(np.array (6,)) for desired link using:
```python
ee_state = robot.ee_state('ee_link')
ee_link_force = ee_state.force_torques
```
